version: '3'

services:
  postgres:
    image: postgres:11.2-alpine
    ports: 
      - "5432:5432"
    restart: always
    environment: 
      - POSTGRES_DB=webbudget
      - POSTGRES_USER=sa_webbudget
      - POSTGRES_PASSWORD=sa_webbudget
      - POSTGRES_PORT=5432
  
  webbudget:
    image: arthurgregorio/web-budget-docker
    ports:
      - "9993:9993"
      - "8443:8443"
    depends_on:
      - postgres
    

